name: publish

on:
  push:
    tags:
      - '*'

env:
  POETRY_VERSION: "1.5.1"
  PYTHON_VERSION: "3.11"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Build package
        run: |
          poetry build
      - name: Upload distribution files
        uses: actions/upload-artifact@v3
        with:
          name: distribution-files
          path: dist/
      - name: Publish package on PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
